### ISSUE TITLE
convert prose to steps?

### ISSUE THREAD

**Issue by story645** [DHRI-Curriculum/mapping#6]
After DHRI of course, but I think some of the instructions could be clearer if things were broken out into a numerical list of steps. For example:

>As you can see from the shapes in the layer, this is a polygon vector layer. Each polygon represents a census block, and all together compose the shape of Manhattan. Note that the color of your layer might be different from the one in the images of this tutorial; QGIS chooses layer colors at random when you first open or create one. If for any reason you’d like to change the color of the layer, you can do it by double-clicking on the layer name in the Layers Panel (“061blk00s tgr061…”) to bring up the Layer Properties box. There, you can click on the Style tab on the left side and you’ll be able to customize the look and color of the layer. To change the color, click on the colored bar drop-down where it says “Color”. Above it, you’ll notice a transparency bar, which can be useful if you want to visualize more than one layer that overlaps. Go ahead and experiment with the styles and choose a visualization to your liking.

Could maybe be:

> As you can see from the shapes in the layer, this is a polygon vector layer. Each polygon represents a census block, and all together compose the shape of Manhattan. Note that the color of your layer might be different from the one in the images of this tutorial; QGIS chooses layer colors at random when you first open or create one. If for any reason you’d like to change the color of the layer, you can do it by:
> 1. Double-click on the layer name in the Layers Panel (“061blk00s tgr061…”) to bring up the Layer Properties box.
> 2. Click on the Style tab on the left side and you’ll be able to customize the look and color of the layer. 
> 3. To change the color, click on the colored bar drop-down where it says “Color”. Above it, you’ll notice a transparency bar, which can be useful if you want to visualize more than one layer that overlaps. 
>
> Go ahead and experiment with the styles and choose a visualization to your liking.
> 

With most of those instructions in a footnote if they're not immediately relevant.

**Comment by dhinstitutes** [comment]
@javo0101 - what do you think of the suggestions above? Is this something you want to do before we start our final push towards finishing the GitBook?

**Comment by kallewesterling** [comment]
Assigning this to you @javo0101 for the time being. Let me know if you want me to go over the repo and suggest edits in a pull request! I'd be happy to!

**Comment by kallewesterling** [comment]
@javo0101 - any updates here? How does your semester look moving forward? Do you think you could provide me with a date when you think this could be done?

**Comment by javo0101** [comment]
Hi Kalle, sorry for the long delay. I'm working on it today! Things were crazy but they're starting to normalize now. So I'll take care of it! Thanks for your patience!


On Sat, Nov 24, 2018 at 12:50 PM Kalle Westerling <notifications@github.com<mailto:notifications@github.com>> wrote:

@javo0101<https://github.com/javo0101> - any updates here? How does your semester look moving forward? Do you think you could provide me with a date when you think this could be done?

**Comment by kallewesterling** [comment]
No worries at all! I see that you've worked on it and am looking forward to seeing the fruits of your labor!!!
